### ISSUE TITLE
Nycta Taxidermy Sizes

### ISSUE THREAD

**Issue by Decollates** [Decollates/MOD-ARK-Nyctatyrannus#14]
- Nycta Rex seems to be a 1.0 size of the live Nycta, making it oversized compared to the rest of the taxidermy bases. Tested on all sizes of taxidermy bases. (Screenshots provided)
![346110_20231112175246_1](https://github.com/Decollates/MOD-ARK-Nyctatyrannus/assets/44717221/d661b95d-1e29-45f5-a22e-975785802844)
![346110_20231112175253_1](https://github.com/Decollates/MOD-ARK-Nyctatyrannus/assets/44717221/ca4d4a64-287f-4ab0-bcb7-8d08e343433a)

**Comment by Decollates** [comment]
Fixed for the subspecies of Nycta, but not for the alphas. 

![346110_20231218151337_1](https://github.com/Decollates/MOD-ARK-Nyctatyrannus/assets/44717221/95c5b7f3-355c-49a6-a23d-74bcbc3966b6)

**Comment by bluescapes** [comment]
Done!

**Comment by Decollates** [comment]
Completed!
