### ISSUE TITLE
Nycta Spawns - Ragnarok

### ISSUE THREAD

**Issue by Decollates** [Decollates/MOD-ARK-Nyctatyrannus#16]
- When testing on Ragnarok, all species of Nyctas except Imperator were definitely on the Very High end of population numbers. I'd like for that to be reduced by 75%.

**Comment by Decollates** [comment]
Spawns are still very high, but don't seem to be overwhelming on Ragnarok compared to before. Still keeping this open for further tweaking.

**Comment by bluescapes** [comment]
The only way I can accomplish this is by lowering spawns across the board, since Ragnarok uses a lot of vanilla containers. Nyctas will certainly still be plentiful though, relatively speaking.

Will tweak those lower and we'll see how that goes!

**Comment by Decollates** [comment]
This is definitely what I'm looking for with population numbers. 

![image](https://github.com/Decollates/MOD-ARK-Nyctatyrannus/assets/44717221/edac7837-fc65-44ee-a413-b213615c018f)
![image](https://github.com/Decollates/MOD-ARK-Nyctatyrannus/assets/44717221/d6823277-e52d-4bf9-b875-1af40f919be0)
![image](https://github.com/Decollates/MOD-ARK-Nyctatyrannus/assets/44717221/0429ec45-9cab-4d12-b996-4f041104b92c)
![image](https://github.com/Decollates/MOD-ARK-Nyctatyrannus/assets/44717221/6c5e8224-2b05-4df0-aff7-91c9491713ec)
