### ISSUE TITLE
Nycta's Strength Roar

### ISSUE THREAD

**Issue by Decollates** [Decollates/MOD-ARK-Nyctatyrannus#19]
- Nycta's Strength Roar: Cannot move while roaring, replace sound with `Nycta_Adult_Broad_1.wav` `Nycta_Adult_Broad_2.wav` and/or `Nycta_Adult_Broad_4.wav` Extend cooldown to conclude after the buff expires. Please add the same cooldown text that the Nycta Rex gets for its charged bite not being ready.

**Comment by Decollates** [comment]
Everything asked for has been implemented, with the exception of the cooldown warning text when the cooldown is still active.

**Comment by bluescapes** [comment]
Done!

**Comment by Decollates** [comment]
Is it possible that the cooldown text be the same as the red text as the charge bite cooldown? (Same thing for the Nycta's Resolve roar.)

![346110_20240103194249_1](https://github.com/Decollates/MOD-ARK-Nyctatyrannus/assets/44717221/d7e86fd9-a60d-4976-99d6-2a3853a8906d)

**Comment by bluescapes** [comment]
I'm a little confused, the roar has the same cooldown text as the bite. I did forget to hide the "cooldown buff" from the HUD though, so I will do that as well.

**Comment by Decollates** [comment]
Corrected!
