### ISSUE TITLE
Taming - No Sleep Sound

### ISSUE THREAD

**Issue by Decollates** [Decollates/MOD-ARK-Nyctatyrannus#2]
- When knocked out, Nyctas do not have the `Nycta_Adult_Sleep_Loop.wav` play.

**Comment by Decollates** [comment]
### Dec 3 update

Sound appears to play, but is so low in volume that you almost cannot hear it unless you're actively looking for it.

**Comment by bluescapes** [comment]
Done, made that 30% louder.

**Comment by Decollates** [comment]
I can hear the sound now - however, it just appears to be the "inhale" of the snore. May want to try replacing the sound with `Nycta_Adult_Sleep_Loop.wav` in the list of sleep sounds.

**Comment by bluescapes** [comment]
I changed up the cue to include the exhale sounds (and added some variation) so this should be fixed!

**Comment by Decollates** [comment]
Perfect! Closing!
