### ISSUE TITLE
Taming - No sound plays with "Taming Success" animation

### ISSUE THREAD

**Issue by Decollates** [Decollates/MOD-ARK-Nyctatyrannus#20]
The animation is meant to play with the `Nycta_Adult_Broad_1` `Nycta_Adult_Broad_2` and `Nycta_Adult_Broad_4` - currently, no sound plays with the animation.

**Comment by bluescapes** [comment]
Done!

**Comment by Decollates** [comment]
Sound and an animation plays, but it doesn't seem to be the taming success animation like so: 
![blender_axih0flMj8](https://github.com/Decollates/MOD-ARK-Nyctatyrannus/assets/44717221/23b90284-89bb-437f-9749-5b6fbb4f6376)

**Comment by bluescapes** [comment]
I don't have that one in my kit currently, but I'll find it and make sure to use it!

**Comment by Decollates** [comment]
Corrected and closed!
