### ISSUE TITLE
Imperator - Nycta's Resolve Call Animation

### ISSUE THREAD

**Issue by Decollates** [Decollates/MOD-ARK-Nyctatyrannus#21]
I appreciate using the custom animation, but is it possible to use the fear/frightened animation for this? (I can't look up the actual animation's name at this moment)

**Comment by bluescapes** [comment]
If it's the Nycta Fear call, that's already being used. I'm gonna assume it's the Started roar, which I'll switch it to!

**Comment by Decollates** [comment]
Completed!
