### ISSUE TITLE
Nycta Feces Prompts

### ISSUE THREAD

**Issue by Decollates** [Decollates/MOD-ARK-Nyctatyrannus#9]
- Prompting to poop has feces go through ground?? Eggs (fertilized and non) do not fall through ground. Testing location: flat dunes in Ragnarok

**Comment by Decollates** [comment]
Still happening when riding Nyctas.

**Comment by bluescapes** [comment]
Done!

**Comment by Decollates** [comment]
Feces are now landing, but now the Nyctas are making two poops, like wyverns LOL. 

![346110_20240103185541_1](https://github.com/Decollates/MOD-ARK-Nyctatyrannus/assets/44717221/67f14459-11eb-4193-a365-902a06d5faf0)

**Comment by bluescapes** [comment]
Fixed!

**Comment by Decollates** [comment]
Closed!
